name: .NET CI

on:
  push:
   branches: ["main", "task01"]
   branches-ignore: ["feature/ci", "fix/ci"]
  pull_request:
    branches: ["main"]
    branches-ignore: ["feature/ci", "fix/ci"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
